#!/usr/bin/env python3

import os

def convert(moxfield_script):
    maps = {
        "valgavoth.txt": "Endless Pain and Suffering",
        "edgar.txt": "Blood Thirst",
        "axonil.txt": "2nd Degree Burns",
        "axonil2.txt": "3rd Degree Burns",
        "hearthhull.txt": "Terraform",
        "toph.txt": "Toph Gruul",
        "toph2.txt": "Toph2",
        "toph3.txt": "Toph3",
        "hashaton.txt": "Hashaton",
        "sephiroth.txt": "Limitless Emblems",
        "zurgo.txt": "Mardu Surge",
        "greengoblin.txt": "Ultimate Green Goblin",
        "hakbal.txt": "Merfolk Explorers",
        "vren2.txt": "Vren Bracket 2",
        "elas.txt": "Elas",
        "elfs.txt": "Elfi cazzuti",
        "braids.txt": "Braids Aristocrat",
    }

    # Create lists directory if it doesn't exist
    lists_dir = os.path.expanduser('~/.forge/lists')
    os.makedirs(lists_dir, exist_ok=True)

    # Create output directory if it doesn't exist
    output_dir = os.path.expanduser("~/.forge/decks/commander")
    os.makedirs(output_dir, exist_ok=True)

    # Convert each list to a Forge deck
    for file_name, deck_name in maps.items():
        cmd = f'{moxfield_script} --name "{deck_name}" -i {lists_dir}/"{file_name}" -o {output_dir}/"{deck_name}.dck"'
        print('%s%s%s' % (Colors.BOLD, cmd, Colors.END))
        os.system(os.path.expanduser(cmd))

class Colors:
    """ ANSI color codes """
    BLACK = "\033[0;30m"
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    BROWN = "\033[0;33m"
    BLUE = "\033[0;34m"
    PURPLE = "\033[0;35m"
    CYAN = "\033[0;36m"
    LIGHT_GRAY = "\033[0;37m"
    DARK_GRAY = "\033[1;30m"
    LIGHT_RED = "\033[1;31m"
    LIGHT_GREEN = "\033[1;32m"
    YELLOW = "\033[1;33m"
    LIGHT_BLUE = "\033[1;34m"
    LIGHT_PURPLE = "\033[1;35m"
    LIGHT_CYAN = "\033[1;36m"
    LIGHT_WHITE = "\033[1;37m"
    BOLD = "\033[1m"
    FAINT = "\033[2m"
    ITALIC = "\033[3m"
    UNDERLINE = "\033[4m"
    BLINK = "\033[5m"
    NEGATIVE = "\033[7m"
    CROSSED = "\033[9m"
    END = "\033[0m"
    # cancel SGR codes if we don't write to a terminal
    if not __import__("sys").stdout.isatty():
        for _ in dir():
            if isinstance(_, str) and _[0] != "_":
                locals()[_] = ""
    else:
        # set Windows console in VT mode
        if __import__("platform").system() == "Windows":
            kernel32 = __import__("ctypes").windll.kernel32
            kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
            del kernel32

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.dirname(script_dir)
    moxfield_script = os.path.join(parent_dir, 'moxfield_to_forge.py')

    if not os.path.isfile(moxfield_script):
        print(f"Error: {moxfield_script} not found.")
    else:
        convert(moxfield_script)
